
Cypress.on('uncaught:exception', (err, runnable) => {
    // retornar false aqu√≠ evita que Cypress
    // falle la prueba
    return false;
});